server:
  port: 8081
spring:
  datasource:
   url: jdbc:mysql://${DB_HOST:localhost}:3306/employee_service
   username: root
   password: Admin@1234
   driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  application:
    name: EMPLOYEE-SERVICE
eureka:
  instance:
    client:
      serverUrl:
        defaultZone=http://localhost:8761/eureka
